Revert "ci(test): Test out curl flags to see if it fails as expected"
This reverts commit bd11cb5805ed7dffdd5799acb4d41b5bb5c1686e.

Yes, it works:

```console
$ md bin\win && cd bin\win && curl.exe -fsSL -o metanorma "https://github.com/metanorma/packed-mn/releases/latest/download/metanorma-windows-x86_64.exe"
curl: (22) The requested URL returned error: 404
error Command failed with exit code 22.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 22.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

See: https://github.com/paneron/paneron/actions/runs/13453796568/job/37593262859#step:7:10